# TCL File Generated by Component Editor 18.1
# Thu Mar 19 20:19:42 CET 2020
# DO NOT MODIFY


# 
# W9825G6KH_SDRAMController_125MHz_CL3_2MMPort "W9825G6KH_SDRAMController_125MHz_CL3_2MMPort" v1.0
#  2020.03.19.20:19:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module W9825G6KH_SDRAMController_125MHz_CL3_2MMPort
# 
set_module_property DESCRIPTION ""
set_module_property NAME W9825G6KH_SDRAMController_125MHz_CL3_2MMPort
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME W9825G6KH_SDRAMController_125MHz_CL3_2MMPort
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL W9825G6KH_SDRAMController_125MHz_CL3_2MMPort
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file W9825G6KH_SDRAMController_125MHz_CL3_2MMPort.v VERILOG PATH W9825G6KH_SDRAMController_125MHz_CL3_2MMPort.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_wr_mem
# 
add_interface avalon_slave_wr_mem avalon end
set_interface_property avalon_slave_wr_mem addressUnits WORDS
set_interface_property avalon_slave_wr_mem associatedClock clock
set_interface_property avalon_slave_wr_mem associatedReset reset
set_interface_property avalon_slave_wr_mem bitsPerSymbol 8
set_interface_property avalon_slave_wr_mem burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_wr_mem burstcountUnits WORDS
set_interface_property avalon_slave_wr_mem explicitAddressSpan 0
set_interface_property avalon_slave_wr_mem holdTime 0
set_interface_property avalon_slave_wr_mem linewrapBursts false
set_interface_property avalon_slave_wr_mem maximumPendingReadTransactions 0
set_interface_property avalon_slave_wr_mem maximumPendingWriteTransactions 0
set_interface_property avalon_slave_wr_mem readLatency 0
set_interface_property avalon_slave_wr_mem readWaitTime 1
set_interface_property avalon_slave_wr_mem setupTime 0
set_interface_property avalon_slave_wr_mem timingUnits Cycles
set_interface_property avalon_slave_wr_mem writeWaitTime 0
set_interface_property avalon_slave_wr_mem ENABLED true
set_interface_property avalon_slave_wr_mem EXPORT_OF ""
set_interface_property avalon_slave_wr_mem PORT_NAME_MAP ""
set_interface_property avalon_slave_wr_mem CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_wr_mem SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_wr_mem wr_addr address Input 24
add_interface_port avalon_slave_wr_mem wr_be_n byteenable_n Input 2
add_interface_port avalon_slave_wr_mem wr_data writedata Input 16
add_interface_port avalon_slave_wr_mem wr_n write_n Input 1
add_interface_port avalon_slave_wr_mem wr_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_wr_mem embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_wr_mem embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_wr_mem embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_wr_mem embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_slave_rd_mem
# 
add_interface avalon_slave_rd_mem avalon end
set_interface_property avalon_slave_rd_mem addressUnits WORDS
set_interface_property avalon_slave_rd_mem associatedClock clock
set_interface_property avalon_slave_rd_mem associatedReset reset
set_interface_property avalon_slave_rd_mem bitsPerSymbol 8
set_interface_property avalon_slave_rd_mem burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_rd_mem burstcountUnits WORDS
set_interface_property avalon_slave_rd_mem explicitAddressSpan 0
set_interface_property avalon_slave_rd_mem holdTime 0
set_interface_property avalon_slave_rd_mem linewrapBursts false
set_interface_property avalon_slave_rd_mem maximumPendingReadTransactions 1
set_interface_property avalon_slave_rd_mem maximumPendingWriteTransactions 0
set_interface_property avalon_slave_rd_mem readLatency 0
set_interface_property avalon_slave_rd_mem readWaitTime 1
set_interface_property avalon_slave_rd_mem setupTime 0
set_interface_property avalon_slave_rd_mem timingUnits Cycles
set_interface_property avalon_slave_rd_mem writeWaitTime 0
set_interface_property avalon_slave_rd_mem ENABLED true
set_interface_property avalon_slave_rd_mem EXPORT_OF ""
set_interface_property avalon_slave_rd_mem PORT_NAME_MAP ""
set_interface_property avalon_slave_rd_mem CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_rd_mem SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_rd_mem rd_addr address Input 24
add_interface_port avalon_slave_rd_mem rd_data readdata Output 16
add_interface_port avalon_slave_rd_mem rd_n read_n Input 1
add_interface_port avalon_slave_rd_mem rd_valid readdatavalid Output 1
add_interface_port avalon_slave_rd_mem rd_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave_rd_mem embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_rd_mem embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_rd_mem embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_rd_mem embeddedsw.configuration.isPrintableDevice 0


# 
# connection point dram_if
# 
add_interface dram_if conduit end
set_interface_property dram_if associatedClock clock
set_interface_property dram_if associatedReset ""
set_interface_property dram_if ENABLED true
set_interface_property dram_if EXPORT_OF ""
set_interface_property dram_if PORT_NAME_MAP ""
set_interface_property dram_if CMSIS_SVD_VARIABLES ""
set_interface_property dram_if SVD_ADDRESS_GROUP ""

add_interface_port dram_if zs_addr dram_address Output 13
add_interface_port dram_if zs_ba dram_bankselect Output 2
add_interface_port dram_if zs_cas_n dram_cas_n Output 1
add_interface_port dram_if zs_cke dram_cke Output 1
add_interface_port dram_if zs_cs_n dram_cs_n Output 1
add_interface_port dram_if zs_dq dram_data Bidir 16
add_interface_port dram_if zs_dqm dram_dqm Output 2
add_interface_port dram_if zs_ras_n dram_ras_n Output 1
add_interface_port dram_if zs_we_n dram_we Output 1

